### ISSUE TITLE
Unable to run launch file. Need help 

### ISSUE THREAD

**Issue by Weiquan1** [pradhanshrijal/pcdet_ros2#1]
[pcdet-1] Traceback (most recent call last):
[pcdet-1]   File "/root/hand_ws/install/pcdet_ros2/lib/pcdet_ros2/pcdet", line 33, in <module>
[pcdet-1]     sys.exit(load_entry_point('pcdet-ros2', 'console_scripts', 'pcdet')())
[pcdet-1]   File "/root/hand_ws/install/pcdet_ros2/lib/pcdet_ros2/pcdet", line 25, in importlib_load_entry_point
[pcdet-1]     return next(matches).load()
[pcdet-1]   File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
[pcdet-1]     module = import_module(match.group('module'))
[pcdet-1]   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
[pcdet-1]     return _bootstrap._gcd_import(name[level:], package, level)
[pcdet-1]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
[pcdet-1]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
[pcdet-1]   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
[pcdet-1]   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
[pcdet-1]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
[pcdet-1]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[pcdet-1]   File "/root/hand_ws/build/pcdet_ros2/pcdet_ros2/pcdet_node.py", line 25, in <module>
[pcdet-1]     import ros2_numpy
[pcdet-1]   File "/root/hand_ws/install/ros2_numpy/local/lib/python3.10/dist-packages/ros2_numpy/__init__.py", line 9, in <module>
[pcdet-1]     from . import geometry
[pcdet-1]   File "/root/hand_ws/install/ros2_numpy/local/lib/python3.10/dist-packages/ros2_numpy/geometry.py", line 3, in <module>
[pcdet-1]     import tf_transformations as transformations
[pcdet-1]   File "/opt/ros/humble/lib/python3.10/site-packages/tf_transformations/__init__.py", line 46, in <module>
[pcdet-1]     import transforms3d
[pcdet-1]   File "/usr/lib/python3/dist-packages/transforms3d/__init__.py", line 10, in <module>
[pcdet-1]     from . import quaternions
[pcdet-1]   File "/usr/lib/python3/dist-packages/transforms3d/quaternions.py", line 27, in <module>
[pcdet-1]     _MAX_FLOAT = np.maximum_sctype(np.float)
[pcdet-1]   File "/usr/local/lib/python3.10/dist-packages/numpy/__init__.py", line 400, in __getattr__
[pcdet-1]     raise AttributeError(
[pcdet-1] AttributeError: `np.maximum_sctype` was removed in the NumPy 2.0 release. Use a specific dtype instead. You should avoid relying on any implicit mechanism and select the largest dtype of a kind explicitly in the code.
[ERROR] [pcdet-1]: process has died [pid 1089, exit code 1, cmd '/root/hand_ws/install/pcdet_ros2/lib/pcdet_ros2/pcdet --ros-args -r __node:=pcdet --params-file /tmp/tmpakklyecn --params-file /tmp/launch_params_ofyl3skx -r input:=/kitti/point_cloud -r output:=cloud_detections'].

1. All systems requirements were exactly the same.
2. Ran python3 setup.py install as well as some other packages.
 Somehow couldn't get the launch file to run.

**Comment by pradhanshrijal** [comment]
Can you try to install numpy 1.x.x and try again

**Comment by Weiquan1** [comment]
> Can you try to install numpy 1.x.x and try again

(openpcdet) root@ai:~/hand_ws# conda list | grep numpy
numpy                     1.13.3           py38he85021b_4  
(openpcdet) root@ai:~/hand_ws# pip list | grep numpy
numpy                                1.13.3
ros2-numpy                           2.0.12

downgraded to version <2.0 but still getting the same error. Is there anything else that i can check for?
