### ISSUE TITLE
No bounding box shown in Rviz2.

### ISSUE THREAD

**Issue by Weiquan1** [pradhanshrijal/pcdet_ros2#2]
I ran into a problem where there is detection but the bounding box is not showing. In the topics section, the /cloud_detection is not being shown in rviz2.
![Screenshot from 2024-12-30 17-25-10](https://github.com/user-attachments/assets/02409a25-8694-4362-abdd-e7a62d5032f5)

**Comment by WangYiZhouKIT** [comment]
Hi, how do you show the detection on rviz2?

**Comment by shrijalpradhandlr** [comment]
Please check the [vision_msgs/vision_msgs_rviz_plugins](https://github.com/ros-perception/vision_msgs/tree/ros2/vision_msgs_rviz_plugins)
